use serde::{Deserialize, Serialize};

use crate::infrastructure::models::pjsip_realtime::enums::{
    pjsip_realtime_common_enums::TurnOnOff,
    pjsip_auth_enums::AuthType,
    pjsip_endpoint_enums::{*},
};

// SIP-UDP方式のPJSIP REALTIME 情報
// データベース上では、id以外のカラムはNULLABLEです。
// 1. データを登録するカラムでは Optionを外します。
//    必ず値を設定します。
// 2. データを登録しないカラムはコメントアウトします。

// insert into ps_auths (id, auth_type, password, username) values ...;
// insert into ps_aors (id, default_expiration, max_contacts, minimum_expiration, qualify_frequency, maximum_expiration, qualify_timeout) values ...;
// insert into ps_endpoints (id, transport, aors, context, disallow, allow, direct_media, force_rport, rewrite_contact, rtp_symmetric, media_encryption, from_domain, from_user) values ...;

#[derive(Clone, Debug, Serialize, Deserialize, sqlx::FromRow)]
pub struct PsAuthForUdp {
    pub id: String,
    pub auth_type: AuthType, // AuthType enum('md5','userpass','google_oauth')
    pub password: String,
    // pub realm: Option<String>,
    pub username: String,
    // pub refresh_token: Option<String>,
    // pub oauth_clientid: Option<String>,
    // pub oauth_secret: Option<String>,
    // pub password_digest: Option<String>,
    // pub supported_algorithms_uas: Option<String>,
    // pub supported_algorithms_uac: Option<String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, sqlx::FromRow)]
pub struct PsAorForUdp {
    pub id: String,
    // pub contact: Option<String>,
    pub default_expiration: i32,
    // pub mailboxes: Option<String>,
    pub max_contacts: i32,
    pub minimum_expiration: i32,
    pub remove_existing: TurnOnOff, // enum('0','1','off','on','false','true','no','yes')
    pub qualify_frequency: i32,
    // pub authenticate_qualify: Option<TurnOnOff>, // enum('0','1','off','on','false','true','no','yes')
    pub maximum_expiration: i32,
    // pub outbound_proxy: Option<String>,
    // pub support_path: Option<TurnOnOff>, // enum('0','1','off','on','false','true','no','yes')
    pub qualify_timeout: i32,
    // pub voicemail_extension: Option<String>,
    pub remove_unavailable: TurnOnOff, // enum('0','1','off','on','false','true','no','yes')
    // pub qualify_2xx_only: Option<TurnOnOff>, // enum('0','1','off','on','false','true','no','yes')
}

#[derive(Clone, Debug, Serialize, Deserialize, sqlx::FromRow)]
pub struct PsEndpointForUdp {
    pub id: String,
    pub transport: String,
    pub aors: String,
    pub auth: String,
    pub context: String,
    pub disallow: String,
    pub allow: String,
    pub direct_media: TurnOnOff,
    // pub connected_line_method: Option<ConnectMethod>,
    // pub direct_media_method: Option<ConnectMethod>,
    // pub direct_media_glare_mitigation: Option<DirectMediaGlareMitigation>,
    // pub disable_direct_media_on_nat: Option<TurnOnOff>,
    pub dtmf_mode: DtmfMode,
    // pub external_media_address: Option<String>,
    pub force_rport: TurnOnOff,
    // pub ice_support: Option<TurnOnOff>,
    // pub identify_by: Option<String>,
    // pub mailboxes: Option<String>,
    // pub moh_suggest: Option<String>,
    // pub outbound_auth: Option<String>,
    // pub outbound_proxy: Option<String>,
    pub rewrite_contact: TurnOnOff,
    pub rtp_ipv6: TurnOnOff,
    pub rtp_symmetric: TurnOnOff,
    // pub send_diversion: Option<TurnOnOff>,
    // pub send_pai: Option<TurnOnOff>,
    // pub send_rpid: Option<TurnOnOff>,
    // pub timers_min_se: Option<i32>,
    // pub timers: Option<Timers>,
    // pub timers_sess_expires: Option<i32>,
    // pub callerid: Option<String>,
    // pub callerid_privacy: Option<CallerIDPrivacy>,
    // pub callerid_tag: Option<String>,
    // #[sqlx(rename = "100rel")] pub hundred_rel: Option<HundredRel>,
    // pub aggregate_mwi: Option<TurnOnOff>,
    // pub trust_id_inbound: Option<TurnOnOff>,
    // pub trust_id_outbound: Option<TurnOnOff>,
    // pub use_ptime: Option<TurnOnOff>,
    // pub use_avpf: Option<TurnOnOff>,
    pub media_encryption: MediaEncryption,
    // pub inband_progress: Option<TurnOnOff>,
    // pub call_group: Option<String>,
    // pub pickup_group: Option<String>,
    // pub named_call_group: Option<String>,
    // pub named_pickup_group: Option<String>,
    // pub device_state_busy_at: Option<i32>,
    // pub fax_detect: Option<TurnOnOff>,
    // pub t38_udptl: Option<TurnOnOff>,
    // pub t38_udptl_ec: Option<T38UdptlEc>,
    // pub t38_udptl_maxdatagram: Option<i32>,
    // pub t38_udptl_nat: Option<TurnOnOff>,
    // pub t38_udptl_ipv6: Option<TurnOnOff>,
    // pub tone_zone: Option<String>,
    // pub language: Option<String>,
    // pub one_touch_recording: Option<TurnOnOff>,
    // pub record_on_feature: Option<String>,
    // pub record_off_feature: Option<String>,
    // pub rtp_engine: Option<String>,
    // pub allow_transfer: Option<TurnOnOff>,
    // pub allow_subscribe: Option<TurnOnOff>,
    // pub sdp_owner: Option<String>,
    // pub sdp_session: Option<String>,
    // pub tos_audio: Option<String>,
    // pub tos_video: Option<String>,
    // pub sub_min_expiry: Option<i32>,
    pub from_domain: String,
    pub from_user: String,
    // pub mwi_from_user: Option<String>,
    // pub dtls_verify: Option<String>,
    // pub dtls_rekey: Option<String>,
    // pub dtls_cert_file: Option<String>,
    // pub dtls_private_key: Option<String>,
    // pub dtls_cipher: Option<String>,
    // pub dtls_ca_file: Option<String>,
    // pub dtls_ca_path: Option<String>,
    // pub dtls_setup: Option<DtlsSetup>,
    // pub srtp_tag_32: Option<TurnOnOff>,
    // pub media_address: Option<String>,
    // pub redirect_method: Option<RedirectMethod>,
    // pub set_var: Option<String>,
    // pub cos_audio: Option<i32>,
    // pub cos_video: Option<i32>,
    // pub message_context: Option<String>,
    // pub force_avp: Option<TurnOnOff>,
    // pub media_use_received_transport: Option<TurnOnOff>,
    // pub accountcode: Option<String>,
    // pub user_eq_phone: Option<TurnOnOff>,
    // pub moh_passthrough: Option<TurnOnOff>,
    // pub media_encryption_optimistic: Option<TurnOnOff>,
    // pub rpid_immediate: Option<TurnOnOff>,
    // pub g726_non_standard: Option<TurnOnOff>,
    // pub rtp_keepalive: Option<i32>,
    // pub rtp_timeout: Option<i32>,
    // pub rtp_timeout_hold: Option<i32>,
    // pub bind_rtp_to_media_address: Option<TurnOnOff>,
    // pub voicemail_extension: Option<String>,
    // pub mwi_subscribe_replaces_unsolicited: Option<TurnOnOff>,
    // pub deny: Option<String>,
    // pub permit: Option<String>,
    // pub acl: Option<String>,
    // pub contact_deny: Option<String>,
    // pub contact_permit: Option<String>,
    // pub contact_acl: Option<String>,
    // pub subscribe_context: Option<String>,
    // pub fax_detect_timeout: Option<i32>,
    // pub contact_user: Option<String>,
    // pub preferred_codec_only: Option<TurnOnOff>,
    // pub asymmetric_rtp_codec: Option<TurnOnOff>,
    // pub rtcp_mux: Option<TurnOnOff>,
    // pub allow_overlap: Option<TurnOnOff>,
    // pub refer_blind_progress: Option<TurnOnOff>,
    // pub notify_early_inuse_ringing: Option<TurnOnOff>,
    // pub max_audio_streams: Option<i32>,
    // pub max_video_streams: Option<i32>,
    // pub webrtc: Option<TurnOnOff>,
    // pub dtls_fingerprint: Option<DtlsFingerprint>,
    // pub incoming_mwi_mailbox: Option<String>,
    // pub bundle: Option<TurnOnOff>,
    // pub dtls_auto_generate_cert: Option<TurnOnOff>,
    // pub follow_early_media_fork: Option<TurnOnOff>,
    // pub accept_multiple_sdp_answers: Option<TurnOnOff>,
    // pub suppress_q850_reason_headers: Option<TurnOnOff>,
    // pub trust_connected_line: Option<TurnOnOff>,
    // pub send_connected_line: Option<TurnOnOff>,
    // pub ignore_183_without_sdp: Option<TurnOnOff>,
    // pub codec_prefs_incoming_offer: Option<String>,
    // pub codec_prefs_outgoing_offer: Option<String>,
    // pub codec_prefs_incoming_answer: Option<String>,
    // pub codec_prefs_outgoing_answer: Option<String>,
    // pub stir_shaken: Option<TurnOnOff>,
    // pub send_history_info: Option<TurnOnOff>,
    // pub allow_unauthenticated_options: Option<TurnOnOff>,
    // pub t38_bind_udptl_to_media_address: Option<TurnOnOff>,
    // pub geoloc_incoming_call_profile: Option<String>,
    // pub geoloc_outgoing_call_profile: Option<String>,
    // pub incoming_call_offer_pref: Option<IncomingCallOfferPref>,
    // pub outgoing_call_offer_pref: Option<OutgoingCallOfferPref>,
    // pub stir_shaken_profile: Option<String>,
    // pub security_negotiation: Option<SecurityNegotiation>,
    // pub security_mechanisms: Option<String>,
    // pub send_aoc: Option<TurnOnOff>,
    // pub overlap_context: Option<String>,
    // pub tenantid: Option<String>,
    // pub suppress_moh_on_sendonly: Option<TurnOnOff>,
}








